export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  COLLEGE_ADMIN: 'COLLEGE_ADMIN',
  FACULTY: 'FACULTY',
  STUDENT: 'STUDENT',
  PLACEMENT_OFFICER: 'PLACEMENT_OFFICER',
};

export const ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LATE: 'LATE',
  EXCUSED: 'EXCUSED',
};

export const ATTENDANCE_THRESHOLDS = {
  SAFE: 75,
  WARNING: 65,
};

export const ASSIGNMENT_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  CLOSED: 'CLOSED',
};

export const SUBMISSION_STATUS = {
  SUBMITTED: 'SUBMITTED',
  GRADED: 'GRADED',
  RESUBMISSION_REQUESTED: 'RESUBMISSION_REQUESTED',
  RESUBMITTED: 'RESUBMITTED',
};

export const REQUEST_TYPES = {
  BONAFIDE: 'BONAFIDE',
  LEAVE: 'LEAVE',
  CERTIFICATE: 'CERTIFICATE',
  ACADEMIC: 'ACADEMIC',
  GENERAL: 'GENERAL',
};

export const REQUEST_STATUS = {
  PENDING: 'PENDING',
  IN_REVIEW: 'IN_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED',
};

export const APPLICATION_STATUS = {
  APPLIED: 'APPLIED',
  SHORTLISTED: 'SHORTLISTED',
  REJECTED: 'REJECTED',
  INTERVIEW: 'INTERVIEW',
  SELECTED: 'SELECTED',
  NOT_SELECTED: 'NOT_SELECTED',
};

export const INTERVIEW_RESULT = {
  PENDING: 'PENDING',
  PASSED: 'PASSED',
  FAILED: 'FAILED',
  ON_HOLD: 'ON_HOLD',
};

export const NOTIFICATION_TYPES = {
  ASSIGNMENT: 'ASSIGNMENT',
  ATTENDANCE_WARNING: 'ATTENDANCE_WARNING',
  REQUEST_UPDATE: 'REQUEST_UPDATE',
  JOB_DRIVE: 'JOB_DRIVE',
  INTERVIEW: 'INTERVIEW',
  PLACEMENT: 'PLACEMENT',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  SYSTEM: 'SYSTEM',
};
